In [1]:
x = [True, "two", 3, [4j, 5, "six"], None]
print(x)

[True, 'two', 3, [4j, 5, 'six'], None]


In [2]:
x.append("spam")
print(x)

[True, 'two', 3, [4j, 5, 'six'], None, 'spam']


In [6]:
type(x)

list

In [8]:
xx = ("one", [], (3j, 4))
type(xx)

tuple

In [9]:
type((42,))

tuple

In [13]:
list(range(0, 5))

[0, 1, 2, 3, 4]

In [11]:
list(range(10, 0, -1))

[10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [14]:
print("lovely\nspam")

lovely
spam


In [15]:
x = ["one", "two", "three", "four", "five"]
x[0]

'one'

In [16]:
x[1]

'two'

In [17]:
x[len(x)-1]

'five'

In [18]:
x[-1]

'five'

In [19]:
"string"[3]

'i'

In [20]:
x[1:4]

['two', 'three', 'four']

In [21]:
x[-1:0:-2]

['five', 'three']

In [22]:
x[3:]

['four', 'five']

In [23]:
x[:2]

['one', 'two']

In [24]:
x[:0]

[]

In [25]:
x[::2]

['one', 'three', 'five']

In [26]:
x[::-1]

['five', 'four', 'three', 'two', 'one']

In [27]:
print(x)

['one', 'two', 'three', 'four', 'five']


In [29]:
x[0] = "spam"

In [30]:
x[-3:] = ["bacon", "eggs"]

In [31]:
print(x)

['spam', 'two', 'bacon', 'eggs']


In [32]:
help("list")

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [34]:
x.insert(1, "bisk")

In [35]:
print(x)

['spam', 'bisk', 'two', 'bacon', 'eggs']


In [37]:
type(x)

list

In [39]:
x.remove("bisk")
print(x)

['spam', 'two', 'bacon', 'eggs']


In [42]:
p = x.pop(0)
print(x)
print(p)

['eggs']
bacon


In [43]:
s = "string"

In [44]:
print(s)

string


In [45]:
s.remove(1)
print(s)

AttributeError: 'str' object has no attribute 'remove'

In [46]:
7 in range(0, 10)

SyntaxError: invalid syntax (Temp/ipykernel_13108/4175706575.py, line 1)

In [47]:
[2, 3] in [ 1, [2, 3], [4, 5, 6] ]

True

In [50]:
help("list")

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [51]:
type(x)

list

In [52]:
print(x)

['eggs']


In [55]:
x.count("eggs")

1

In [56]:
x.index("eggs")

0

In [57]:
x = ["one", "two", "three", "four", "five"]

In [58]:
x.index("three")

2

In [59]:
"spam" + " " + "bacon"

'spam bacon'

In [60]:
[1, 2, 3] + [4]

[1, 2, 3, 4]

In [61]:
"spam" * 3

'spamspamspam'

In [62]:
(1, 2) + (3, 4)

(1, 2, 3, 4)

In [63]:
(1, 3) * 3

(1, 3, 1, 3, 1, 3)

In [64]:
x = {
    "a": [1, 2, 3],
    "b": 7,
    "z": "spam!"
}
print(x)

{'a': [1, 2, 3], 'b': 7, 'z': 'spam!'}


In [65]:
dict(a=[1, 2, 3], b=7, z="spam!")

{'a': [1, 2, 3], 'b': 7, 'z': 'spam!'}

In [66]:
type(x)

dict

In [67]:
x["a"]

[1, 2, 3]

In [68]:
"a" in x, 0 not in x, "z" in x, "w" in x

(True, True, True, False)

In [69]:
x["f"] = "more spam!"

In [70]:
print(x)

{'a': [1, 2, 3], 'b': 7, 'z': 'spam!', 'f': 'more spam!'}


In [71]:
import requests

In [72]:
x = requests.get("https://api.github.com/users/gagolews/starred").json()

In [73]:
type(x)

list

In [74]:
x[3]

{'id': 176080416,
 'node_id': 'MDEwOlJlcG9zaXRvcnkxNzYwODA0MTY=',
 'name': 'Clustering-via-Nonsmooth-Optimization',
 'full_name': 'SnTa2019/Clustering-via-Nonsmooth-Optimization',
 'private': False,
 'owner': {'login': 'SnTa2019',
  'id': 47778511,
  'node_id': 'MDQ6VXNlcjQ3Nzc4NTEx',
  'avatar_url': 'https://avatars.githubusercontent.com/u/47778511?v=4',
  'gravatar_id': '',
  'url': 'https://api.github.com/users/SnTa2019',
  'html_url': 'https://github.com/SnTa2019',
  'followers_url': 'https://api.github.com/users/SnTa2019/followers',
  'following_url': 'https://api.github.com/users/SnTa2019/following{/other_user}',
  'gists_url': 'https://api.github.com/users/SnTa2019/gists{/gist_id}',
  'starred_url': 'https://api.github.com/users/SnTa2019/starred{/owner}{/repo}',
  'subscriptions_url': 'https://api.github.com/users/SnTa2019/subscriptions',
  'organizations_url': 'https://api.github.com/users/SnTa2019/orgs',
  'repos_url': 'https://api.github.com/users/SnTa2019/repos',
  'events_u

In [75]:
type(x[3])

dict

In [76]:
x[3]["name"]

'Clustering-via-Nonsmooth-Optimization'

In [82]:
x[20]["name"]

'nlopt'

In [90]:
x[7]["name"]

'Alegreya-Sans'

In [102]:
yy = list("spam")

In [91]:
tuple(range(0,10,2))

(0, 2, 4, 6, 8)

In [92]:
help("list")

Help on class list in module builtins:

class list(object)
 |  list(iterable=(), /)
 |  
 |  Built-in mutable sequence.
 |  
 |  If no argument is given, the constructor creates a new empty list.
 |  The argument must be an iterable if specified.
 |  
 |  Methods defined here:
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __contains__(self, key, /)
 |      Return key in self.
 |  
 |  __delitem__(self, key, /)
 |      Delete self[key].
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getitem__(...)
 |      x.__getitem__(y) <==> x[y]
 |  
 |  __gt__(self, value, /)
 |      Return self>value.
 |  
 |  __iadd__(self, value, /)
 |      Implement self+=value.
 |  
 |  __imul__(self, value, /)
 |      Implement self*=value.
 |  
 |  __init__(self, /, *args, **kwargs)
 |      Initialize self.  See help(type(self))

In [112]:
y = [1,2,3,4]
print(y)
print(xx)

[1, 2, 3, 4]
('one', [], (3j, 4))


In [116]:
e = yy.extend(xx)
print(e)
t = (4,5,67,7)
print(t)

None
(4, 5, 67, 7)


In [118]:
e = yy.extend(t)
print(e)

None


In [108]:
range(0, 5)

range(0, 5)

In [122]:
zip(xx)

In [123]:
enumerate(xx)

In [124]:
reversed(xx)

In [125]:
x = [1, "two", ["three", 3j, 3], False] 
for el in x:
    print(el)

1
two
['three', 3j, 3]
False


In [126]:
for i in range(len(x)):
    print(i, x[i], sep=": ")

0: 1
1: two
2: ['three', 3j, 3]
3: False


In [127]:
x = [1,  2,   3,    4,     5]  # for testing
y = [1, 10, 100, 1000, 10000]  # just a test
z = []  # result list – start with an empty one
for i in range(len(x)):
    z.append(x[i] * y[i])
print(z)

[1, 20, 300, 4000, 50000]


In [128]:
import math
def mymin(x):
    """
    The smallest element in an iterable object x.
    We assume that x consists of numbers only.
    """
    curmin = math.inf  # infinity is greater than any other number
    for e in x:
        if e < curmin:
            curmin = e  # a better candidate for the minimum
    return curmin

In [132]:
mymin(y)

1

In [133]:
import numpy as np
result = np.unique([1, 2, 1, 2, 1, 1, 3, 2, 1], return_counts=True)
print(result)

(array([1, 2, 3]), array([5, 3, 1], dtype=int64))


In [134]:
type(result), len(result)

(tuple, 2)

In [135]:
result[0]

array([1, 2, 3])

In [3]:
import numpy as np
values, counts = np.unique([1, 2, 1, 2, 1, 1, 3, 2, 1], return_counts=True)
print(values, counts)

[1 2 3] [5 3 1]


In [9]:
a, *b, c, d = range(10)
print(a, b, c, d, sep="\n")

0
[1, 2, 3, 4, 5, 6, 7]
8
9


In [11]:
def test(a, b, c, d):
    "It is just a test – simply prints the arguments passed"
    print("a = ", a, ", b = ", b, ", c = ", c, ", d = ", d, sep="")

In [17]:
args = [1, 2, 3, 4]
type(args)
test(*args)
test(3,4,5,6)

a = 1, b = 2, c = 3, d = 4
a = 3, b = 4, c = 5, d = 6


In [13]:
kwargs = dict(a=1, c=3, d=4, b=2)
test(**kwargs)

a = 1, b = 2, c = 3, d = 4


In [15]:
test(1, *range(2,4), 4)
test(1, **dict(d=4, c=3, b=2))
test(*range(1,3), **dict(d=4, c=3))

a = 1, b = 2, c = 3, d = 4
a = 1, b = 2, c = 3, d = 4
a = 1, b = 2, c = 3, d = 4


In [18]:
type(args)

list

In [20]:
def test(a, b, *args, **kwargs):
    "simply prints the arguments passed"
    print(
        "a = ", a, ", b = ", b,
        ", args = ", args, ", kwargs = ", kwargs, sep=""
    )

In [21]:
test(1, 2, 3, 4, 5, spam=6, eggs=7)

a = 1, b = 2, args = (3, 4, 5), kwargs = {'spam': 6, 'eggs': 7}


In [22]:
x = [1, 2, 3]
y = x

In [25]:
print(x)
print(y)

[1, 2, 4]
[1, 2, 4]


In [24]:
x[2] = 4

In [26]:
x.append(4)
print(y)

[1, 2, 4, 4]


In [27]:
def myadd(z, i):
    z.append(i)

In [30]:
myadd(x, 5)
myadd(y, 6)
print(x)
print(y)

[1, 2, 4, 4, 5, 6, 5, 6, 5, 6]
[1, 2, 4, 4, 5, 6, 5, 6, 5, 6]


In [32]:
x = [1, 2, 3]
y = x.copy()
x.append(4)
print(y)
print(x)

[1, 2, 3]
[1, 2, 3, 4]


In [33]:
x = [5, 3, 2, 4, 1]
print(sorted(x))
print(x)

[1, 2, 3, 4, 5]
[5, 3, 2, 4, 1]


In [34]:
x.sort()
print(x)

[1, 2, 3, 4, 5]


In [35]:
import random
random.shuffle(x)
print(x)

[2, 1, 5, 4, 3]


In [36]:
import pandas as pd
x = pd.Series([5, 3, 2, 4, 1])
print(list(x.sort_values()))
print(list(x))

[1, 2, 3, 4, 5]
[5, 3, 2, 4, 1]


In [37]:
print(x)

0    5
1    3
2    2
3    4
4    1
dtype: int64


In [40]:
x.sort_values(inplace = True)
print(list(x))
print(x)

[1, 2, 3, 4, 5]
4    1
2    2
1    3
3    4
0    5
dtype: int64
